$INPUT_FIELD_MONITOR = eDP-1

label {
  text = cmd[update:1000] echo "$(~/.local/bin/battery-status-hyprlock)"
  font_size = 20
  font_family = $font ExtraBold
  color = rgba(fb6389ff)

  position = -20, -5
  halign = right
  valign = top
}
