$INPUT_FIELD_MONITOR = eDP-1

label {
  text = cmd[update:1000] echo "󰁹  $(cat /sys/class/power_supply/BAT0/capacity)%"  
  font_size = 20
  font_family = $font ExtraBold
  color = rgba(fb6389ff)

  position = -20, -5
  halign = right
  valign = top
}
